### ISSUE TITLE
defer a requirement?

### ISSUE THREAD

**Issue by ghost** [SentimensRG/txCelery#9]
defer doesn't come installed. Should it be a requirement?

Edit: I misinterpreted the error message.

**Comment by lthibault** [comment]
A bit of context would help.  Could you please provide a code example?

**Comment by ghost** [comment]
trying to run it in virtualenv (in docker specifically) and had to explicitly install defer because your package didn't have it installed, yet failed to import. I'll make a short example sometime.

**Comment by lthibault** [comment]
>explicitly install defer

Do you mean install twisted?

**Comment by lthibault** [comment]
>explicitly install defer

What do you mean by "install defer"?  Do you mean "install twisted"?

I just double-checked `setup.py` and Twisted is listed as a dependency.  Running `pip install txcelery` ought to pull in Twisted which means you should be able to run `from twisted.internet import defer`.

It would be helpful to have a code example reproduces your problem. :)

I'll have a bit of time tomorrow, so if you can submit such an example, I'll take a look at it then.  It should be pretty straightforward to get you up and running.

**Comment by ghost** [comment]
Python 3.5 breaks vs python 2.7, tested via virtualenv with the following files:

requirements.txt
```
txcelery>=1.0.2
redis>=2.10.6
#defer>=1.0.4 - don't really think an external defer vs twisted's defer is helpful, but hey.
```
worker.py
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals
from __future__ import print_function
from txcelery.defer import CeleryClient
from celery import Celery
worker = Celery('tasks', backend='redis', broker='redis://guest@localhost:6379//')

@CeleryClient
@worker.task
def add(a,b):
    return a + b

if __name__ == '__main__':
    worker.start(argv=['celery', 'worker', '-l', 'info'])
```

to reproduce:

```bash
virtualenv lower
source lower/bin/activate
pip install -r requirements.txt
python worker.py
deactivate
```
```bash
virtualenv upper -p python3
source upper/bin/activate
pip install -r requirements.txt
python worker.py
deactivate
```

traceback:
```
Traceback (most recent call last):
  File "worker.py", line 6, in <module>
    from txcelery.defer import CeleryClient
  File "/home/qul/uper/lib/python3.5/site-packages/txcelery/__init__.py", line 4, in <module>
    import defer
ImportError: No module named 'defer'
```

**Comment by ghost** [comment]
tried without my `from __future__ import absolute_import` to the same effect, as if that'd change the problem. :cry:
